WebProgProjeOdev/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebProgProjeOdev.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebProgProjeOdev/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Small Business - Start Bootstrap Template</title>
    <!-- Bootstrap Core CSS -->
    <link href=/Content/"css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href=/Content/"css/small-business.css" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->


</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">                    
                </a>
            </div>
            
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Ana Sayfa", "Index", "Home")</li>
                    <li>@Html.ActionLink("Hakkımızda", "About", "Home")</li>
                    <li>@Html.ActionLink("Iletişim", "Contact", "Home")</li>    
                </ul>
            </div>
            
            
            <!-- /.navbar-collapse -->
        </div>
        @RenderBody()

        
        <!-- /.container -->
    </nav>
    <!-- Page Content -->
    <div class="container">
        <!-- Heading Row -->
        <div class="row">
            <div class="col-md-8">
                <img class="img-responsive img-rounded" src="http://www.borkmansinvestment.com/wp-content/uploads/2015/02/corola-1000x500.jpg" width="1000" height="500" alt="">
           
            </div>
            <!-- /.col-md-8 -->
            
            <div class="col-md-4">
                <h1>VIP RENT A CAR</h1>
                <p>HAFTANIN 7/24 MÜŞTERİLERİN HİZMETEYİZ </p>
            </div>
            <!-- /.col-md-4 -->
        </div>   
        <!-- /.row -->
        <hr>
        <!-- Call to Action Well -->
        <div class="row">
            <div class="col-lg-10">
                <div class="well text-center">
                    TURKIYENIN EN BÜYÜK ARAÇ KIRALAMA SITESI
                </div>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
        <!-- Content Row -->
        <div class="row">
            <div class="col-md-4">
                <h2>ARABALAR</h2>
                <p>AUDI; BMW; MERCEDES BENZ; TOYOTA; RENAULT; VOLVO; VOLKSWAGEN</p>
                <li>@Html.ActionLink("Arabalar","Daha Fazla","More Info")</li>
            </div>
            <!-- /.col-md-4 -->
            <div class="col-md-4">
                <h2>PİCK-UP ARAÇLAR </h2>
                <p>MERCEDES BENZ SPRINTER; VOLKSWAGEN TRANSPORTER; VOLKSWAGEN CADDY</p>
                <li>@Html.ActionLink("Daha Fazla", "More Info")</li>
            </div>
            <!-- /.col-md-4 -->
            <div class="col-md-4">
                <h2>VIP-LINE ARAÇLAR</h2>
                <p>MERCEDES BENZ VITO VIP; VOLKSWAGEN TRASPORTER VIP </p>
                <li>@Html.ActionLink("Daha Fazla", "More Info")</li>
            </div>
            <!-- /.col-md-4 -->
        </div>
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    
                    <p></p>
                    
                </div>
            </div>
        </footer>
      </div>
    
    
    <!-- /.container -->
    <!-- jQuery -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="js/jquery.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>
    
    
    @RenderSection("scripts", required: false)
</body>
</html>